-- DROP TABLE TRANSACTIONS;
-- DROP TABLE ACCOUNTS;
CREATE TABLE IF NOT EXISTS ACCOUNTS(
    ACCOUNT_TYPE CHARACTER VARYING(31) NOT NULL,
    ACCOUNT_NUMBER CHARACTER VARYING(255) PRIMARY KEY,
    ACCOUNT_HOLDER_NUMBER CHARACTER VARYING(255) NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL,
    OVERDRAFT_LIMIT DOUBLE PRECISION,
    MINIMUM_BALANCE DOUBLE PRECISION,
    MONTHLY_INTEREST_RATE DOUBLE PRECISION,
    MINIMUM_BALANCE_IN_MONTH DOUBLE PRECISION,
    IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_TYPE NVARCHAR(20),
    AMOUNT  DOUBLE PRECISION,
    TRANSACTION_DATE DATE,
    SOURCE_ACCOUNT_NUMBER VARCHAR(16),
    TARGET_ACCOUNT_NUMBER VARCHAR(16),
    STATUS VARCHAR(10),
    FEE DOUBLE PRECISION,
    FOREIGN KEY (SOURCE_ACCOUNT_NUMBER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
    FOREIGN KEY (TARGET_ACCOUNT_NUMBER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER)
);