CREATE TABLE IF NOT EXISTS CHECKING_ACCOUNT(
    ACCOUNT_NUMBER VARCHAR(16) PRIMARY KEY,
    ACCOUNT_HOLDER_NUMBER NVARCHAR(50),
    BALANCE DOUBLE,
    OVER_DRAFT_LIMIT DOUBLE
);

CREATE TABLE IF NOT EXISTS SAVING_ACCOUNT(
    ACCOUNT_NUMBER VARCHAR(16) PRIMARY KEY,
    ACCOUNT_HOLDER_NUMBER NVARCHAR(50),
    BALANCE DOUBLE,
    MONTHLY_INTEREST_RATE FLOAT,
    MINIMUM_BALANCE DOUBLE,
    MINIMUM_BAlANCE_IN_MONTH DOUBLE
);